const ORGANIZATION_MODULE = 'ORGANIZATION_MODULE'

export const actionTypes = {
  ORGANIZATION: {
    FETCH: `FETCH_${ORGANIZATION_MODULE}`,
    FETCH_LIST: `FETCH_LIST_${ORGANIZATION_MODULE}`,
    FETCH_STATUS: `FETCH_STATUS_${ORGANIZATION_MODULE}`,
    STORE_NEW: `STORE_NEW_${ORGANIZATION_MODULE}`,
    STORE_DELETE: `STORE_DELETE_${ORGANIZATION_MODULE}`,
  },
}
